spring:
  datasource:
    url:jdbc:mysql://localhost:3306/
    username:root
    password:root
    driverClassName:com.mysql.jdbc.Driver
  profiles:
    active: dev
cloud:
  zookeeper:
    connect-string: 182.92.112.35:2181
    config:
      enable: true
      root: /