server:
  port: 9999
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: tulingmall-auth
    #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.65.232:8848  #注册中心地址
        namespace: 80a98d11-492c-4008-85aa-32d889e9b0d0  #环境隔离
  datasource:
    url: jdbc:mysql://tuling.com:3306/tlmall_oauth?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

tuling:
  jwt:
    keyPairName: jwt.jks
    keyPairAlias: jwt
    keyPairSecret: 123123
    keyPairStoreSecret: 123123
